# -*- coding: utf-8 -*-
"""CricAiBatting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jMJqIL-087NF9F2T1jnBCIhkLCu5Bmyf
"""

import os
from google.colab import drive

if not os.path.exists('/content/drive/MyDrive'):
    drive.mount('/content/drive')
    print("Drive mounted successfully!")
else:
    print("Drive is already mounted.")

import os

path = '/content/drive/MyDrive/CricAI/data/player_features_batting_form.csv'

if os.path.exists(path):
    print("File exists.")
else:
    print("File does not exist.")

!pip install lightgbm pandas scikit-learn joblib -q

import pandas as pd
import numpy as np
import lightgbm as lgb
from sklearn.model_selection import GroupKFold
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import joblib, os

df = pd.read_csv(path)
print(f"[INFO] Loaded {len(df):,} rows")
# df.head(5)

df = pd.read_csv(batting_path)
print(f"[INFO] Loaded {len(df):,} rows")

print("\n ALL TEAMS IN DATASET:")
all_teams = set(df['batting_team'].unique()) | set(df['opponent_team'].unique())
print(sorted(list(all_teams)))

# @title Advanced Batting Performance Model (FINAL SOLUTION)

import lightgbm as lgb
import numpy as np
import pandas as pd
from sklearn.model_selection import GroupKFold
from sklearn.metrics import mean_absolute_error
import joblib
import warnings

warnings.filterwarnings("ignore")

SECTION_LINE = "=" * 60


def print_section(title: str) -> None:
    title = title.strip()
    print(f"\n{SECTION_LINE}")
    print(f" {title}")
    print(SECTION_LINE)

# 1 LOAD DATA

print_section("1 LOAD DATA")
print(" Loading data files...")

# Load batting data (main dataset)
batting_path = "/content/drive/MyDrive/CricAI/data/player_features_batting.csv"
batting_df = pd.read_csv(batting_path)

# Load bowling data for opponent strength calculation
bowling_path = "/content/drive/MyDrive/CricAI/data/player_features_bowling.csv"
bowling_df = pd.read_csv(bowling_path)

print(f" Batting data: {batting_df.shape}")
print(f" Bowling data: {bowling_df.shape}")

# 2 DYNAMIC VENUE & PLAYER PROFILING


def calculate_dynamic_venue_effects(df):
    """
    Dynamically calculate venue effects from historical data
    """
    print(" Calculating dynamic venue effects...")

    venue_stats = (
        df.groupby("venue")
        .agg(
            {
                "runs_scored": ["mean", "std", "count"],
                "strike_rate": "mean",
                "boundaries": "mean",
                "sixes": "mean",
            }
        )
        .round(2)
    )

    venue_stats.columns = [
        "venue_avg_runs",
        "venue_std_runs",
        "match_count",
        "venue_avg_sr",
        "venue_avg_boundaries",
        "venue_avg_sixes",
    ]
    venue_stats = venue_stats.reset_index()

    # Calculate venue factor (compared to overall average)
    overall_avg_runs = df["runs_scored"].mean()
    venue_stats["venue_factor"] = venue_stats["venue_avg_runs"] / overall_avg_runs

    # Categorize venues based on runs scored
    def categorize_venue(row):
        if row["match_count"] < 5:  # Not enough data
            return " NEUTRAL", 1.0

        if row["venue_avg_runs"] >= overall_avg_runs * 1.15:
            return " BATTER'S PARADISE", 1.3
        elif row["venue_avg_runs"] >= overall_avg_runs * 1.05:
            return " HIGH-SCORING", 1.15
        elif row["venue_avg_runs"] <= overall_avg_runs * 0.85:
            return " BOWLER FRIENDLY", 0.8
        elif row["venue_avg_runs"] <= overall_avg_runs * 0.95:
            return " BALANCED", 0.9
        else:
            return " NEUTRAL", 1.0

    venue_stats[["venue_type", "venue_factor_cat"]] = venue_stats.apply(
        lambda x: pd.Series(categorize_venue(x)), axis=1
    )

    # Use a blend of calculated and categorical factors
    venue_stats["final_venue_factor"] = (
        venue_stats["venue_factor"] + venue_stats["venue_factor_cat"]
    ) / 2

    return venue_stats[["venue", "venue_avg_runs", "venue_type", "final_venue_factor"]]


def create_dynamic_player_profiles(df):
    """
    Create dynamic player profiles from historical data
    """
    print(" Creating dynamic player profiles...")

    player_profiles = (
        df.groupby("player_id")
        .agg(
            {
                "player_name": "first",
                "runs_scored": ["mean", "max", "std", "count"],
                "strike_rate": "mean",
                "batting_position": ["mean", "min", "max"],
                "boundaries": "mean",
                "sixes": "mean",
                "balls_faced": "mean",
            }
        )
        .round(2)
    )

    player_profiles.columns = [
        "name",
        "avg_runs",
        "max_runs",
        "std_runs",
        "matches_played",
        "avg_strike_rate",
        "avg_position",
        "min_position",
        "max_position",
        "avg_boundaries",
        "avg_sixes",
        "avg_balls_faced",
    ]
    player_profiles = player_profiles.reset_index()

    # Categorize players dynamically
    def categorize_player(row):
        avg_runs = row["avg_runs"]
        position = row["avg_position"]
        strike_rate = row["avg_strike_rate"]
        matches = row["matches_played"]

        if matches < 5:  # Not enough data
            return " NEW PLAYER"

        if avg_runs > 45 and position <= 3:
            return " WORLD-CLASS TOP ORDER"
        elif avg_runs > 35 and position <= 3:
            return " SOLID TOP ORDER"
        elif avg_runs > 30 and position <= 4:
            return " RELIABLE TOP/MIDDLE"
        elif avg_runs > 25 and position <= 6:
            return " DEPENDABLE MIDDLE ORDER"
        elif avg_runs > 20:
            return " USEFUL MIDDLE/LOWER"
        elif strike_rate > 140:
            return " HARD-HITTING FINISHER"
        elif position >= 7:
            return " BOWLING ALL-ROUNDER"
        else:
            return " UTILITY PLAYER"

    player_profiles["player_type"] = player_profiles.apply(categorize_player, axis=1)

    return player_profiles


print_section("2 DYNAMIC VENUE & PLAYER PROFILING")
# Calculate dynamic profiles
venue_effects = calculate_dynamic_venue_effects(batting_df)
player_profiles = create_dynamic_player_profiles(batting_df)

print(f" Venue effects calculated for {len(venue_effects)} venues")
print(f" Player profiles created for {len(player_profiles)} players")

# 3 OPPONENT BOWLING STRENGTH CALCULATION


def calculate_opponent_bowling_strength(bowling_df, batting_df):
    """
    Calculate comprehensive opponent bowling strength using bowling data
    """
    print(" Calculating opponent bowling strength...")

    # Ensure date is datetime
    bowling_df = bowling_df.copy()
    bowling_df["date"] = pd.to_datetime(bowling_df["date"])
    bowling_df = bowling_df.sort_values(["opponent_team", "date"])

    # Calculate match-level bowling stats for each team
    match_bowling_stats = (
        bowling_df.groupby(["opponent_team", "date", "match_id", "venue"])
        .agg(
            {
                "runs_conceded": "sum",
                "balls_bowled": "sum",
                "wickets_taken": "sum",
                "dot_balls": "sum",
                "overs_bowled": "sum",
            }
        )
        .reset_index()
    )

    # Calculate derived metrics
    match_bowling_stats["economy_rate"] = (
        match_bowling_stats["runs_conceded"] / match_bowling_stats["overs_bowled"]
    ).fillna(6.0)
    match_bowling_stats["wickets_per_match"] = match_bowling_stats["wickets_taken"]
    match_bowling_stats["dot_ball_pct"] = (
        match_bowling_stats["dot_balls"] / match_bowling_stats["balls_bowled"] * 100
    ).fillna(25.0)

    # Calculate rolling averages for recent form (last 5 matches)
    match_bowling_stats["opponent_economy_last_5"] = match_bowling_stats.groupby(
        "opponent_team"
    )["economy_rate"].transform(lambda x: x.rolling(5, min_periods=1).mean())
    match_bowling_stats["opponent_wickets_last_5"] = match_bowling_stats.groupby(
        "opponent_team"
    )["wickets_per_match"].transform(lambda x: x.rolling(5, min_periods=1).mean())
    match_bowling_stats["opponent_dot_pct_last_5"] = match_bowling_stats.groupby(
        "opponent_team"
    )["dot_ball_pct"].transform(lambda x: x.rolling(5, min_periods=1).mean())

    # Venue-specific bowling performance
    venue_bowling_stats = (
        match_bowling_stats.groupby(["opponent_team", "venue"])
        .agg(
            {
                "economy_rate": "mean",
                "wickets_per_match": "mean",
                "dot_ball_pct": "mean",
            }
        )
        .reset_index()
    )
    venue_bowling_stats.columns = [
        "opponent_team",
        "venue",
        "venue_opponent_economy",
        "venue_opponent_wickets",
        "venue_opponent_dot_pct",
    ]

    # Merge venue stats back
    match_bowling_stats = match_bowling_stats.merge(
        venue_bowling_stats, on=["opponent_team", "venue"], how="left"
    )

    # Fill NaN venue stats with overall averages
    overall_avg_economy = match_bowling_stats["economy_rate"].mean()
    overall_avg_wickets = match_bowling_stats["wickets_per_match"].mean()
    overall_avg_dot_pct = match_bowling_stats["dot_ball_pct"].mean()

    match_bowling_stats["venue_opponent_economy"] = match_bowling_stats[
        "venue_opponent_economy"
    ].fillna(overall_avg_economy)
    match_bowling_stats["venue_opponent_wickets"] = match_bowling_stats[
        "venue_opponent_wickets"
    ].fillna(overall_avg_wickets)
    match_bowling_stats["venue_opponent_dot_pct"] = match_bowling_stats[
        "venue_opponent_dot_pct"
    ].fillna(overall_avg_dot_pct)

    # Create composite bowling strength score (lower economy = better bowling)
    match_bowling_stats["bowling_strength_composite"] = (
        (1 - (match_bowling_stats["opponent_economy_last_5"] / 12))
        * 0.4  # Economy component (40%)
        + (match_bowling_stats["opponent_wickets_last_5"] / 10)
        * 0.3  # Wicket component (30%)
        + (match_bowling_stats["opponent_dot_pct_last_5"] / 50)
        * 0.3  # Dot ball component (30%)
    )

    # Normalize to 0-1 scale
    min_strength = match_bowling_stats["bowling_strength_composite"].min()
    max_strength = match_bowling_stats["bowling_strength_composite"].max()
    match_bowling_stats["bowling_strength_norm"] = (
        match_bowling_stats["bowling_strength_composite"] - min_strength
    ) / (max_strength - min_strength + 1e-6)

    # Prepare for merging with batting data
    bowling_strength_features = match_bowling_stats[
        [
            "opponent_team",
            "date",
            "match_id",
            "venue",
            "opponent_economy_last_5",
            "opponent_wickets_last_5",
            "opponent_dot_pct_last_5",
            "venue_opponent_economy",
            "venue_opponent_wickets",
            "venue_opponent_dot_pct",
            "bowling_strength_norm",
        ]
    ]

    return bowling_strength_features


print_section("3 OPPONENT BOWLING STRENGTH CALCULATION")
# Calculate bowling strength
bowling_strength_df = calculate_opponent_bowling_strength(bowling_df, batting_df)
print(f" Bowling strength features calculated: {bowling_strength_df.shape}")

# 4 FEATURE ENGINEERING - ENHANCED FOR BATTING


def safe_convert_season(x):
    try:
        return int(str(x).split("/")[0])
    except Exception:
        return 2023


def create_batting_features(
    df: pd.DataFrame, bowling_strength_df: pd.DataFrame
) -> pd.DataFrame:
    df = df.copy()
    df = df.sort_values(["player_id", "date"])

    print(" Creating enhanced batting features...")

    # Merge bowling strength features
    df["date"] = pd.to_datetime(df["date"])
    df = df.merge(
        bowling_strength_df,
        on=["opponent_team", "date", "match_id", "venue"],
        how="left",
    )

    # Fill any missing bowling strength with median
    if "bowling_strength_norm" in df.columns:
        df["bowling_strength_norm"] = df["bowling_strength_norm"].fillna(
            df["bowling_strength_norm"].median()
        )

    # --- Enhanced lagged features with more windows ---
    df["runs_avg_5_lagged"] = df.groupby("player_id")["runs_scored"].transform(
        lambda x: x.shift(1).rolling(5, min_periods=1).mean()
    )
    df["runs_avg_10_lagged"] = df.groupby("player_id")["runs_scored"].transform(
        lambda x: x.shift(1).rolling(10, min_periods=1).mean()
    )
    df["runs_avg_15_lagged"] = df.groupby("player_id")["runs_scored"].transform(
        lambda x: x.shift(1).rolling(15, min_periods=1).mean()
    )

    # Strike rate features
    df["sr_avg_5_lagged"] = df.groupby("player_id")["strike_rate"].transform(
        lambda x: x.shift(1).rolling(5, min_periods=1).mean()
    )
    df["sr_avg_10_lagged"] = df.groupby("player_id")["strike_rate"].transform(
        lambda x: x.shift(1).rolling(10, min_periods=1).mean()
    )

    # Boundary hitting ability
    df["boundaries_per_ball"] = (df["boundaries"] + df["sixes"]) / df["balls_faced"]
    df["boundaries_per_ball"] = df["boundaries_per_ball"].fillna(0)
    df["boundary_rate_5_lagged"] = df.groupby("player_id")[
        "boundaries_per_ball"
    ].transform(lambda x: x.shift(1).rolling(5, min_periods=1).mean())

    # Dismissal rate (if dismissed)
    if "dismissals" in df.columns:
        df["dismissal_rate"] = df["dismissals"]
        df["dismissal_rate_5_lagged"] = df.groupby("player_id")[
            "dismissal_rate"
        ].transform(lambda x: x.shift(1).rolling(5, min_periods=1).mean())

    # Phase-wise batting performance
    if all(
        col in df.columns for col in ["powerplay_runs", "middle_runs", "death_runs"]
    ):
        df["powerplay_avg"] = df["powerplay_runs"] / (df["powerplay_balls"] + 1e-6)
        df["middle_avg"] = df["middle_runs"] / (df["middle_balls"] + 1e-6)
        df["death_avg"] = df["death_runs"] / (df["death_balls"] + 1e-6)

    # --- Enhanced vs_opponent features ---
    def safe_opponent_avg(group):
        return group.shift(1).rolling(10, min_periods=1).mean()

    df["vs_opponent_avg_10_lagged"] = df.groupby(["player_id", "opponent_team"])[
        "runs_scored"
    ].transform(safe_opponent_avg)

    # Fill NaN values with player's overall average
    player_avg = df.groupby("player_id")["runs_scored"].transform("mean")
    df["vs_opponent_avg_10_lagged"] = df["vs_opponent_avg_10_lagged"].fillna(player_avg)

    # --- Career expectation with multiple windows ---
    df["expected_runs_5"] = df.groupby("player_id")["runs_scored"].transform(
        lambda x: x.shift(1).rolling(5, min_periods=1).mean()
    )
    df["expected_runs_10"] = df.groupby("player_id")["runs_scored"].transform(
        lambda x: x.shift(1).rolling(10, min_periods=1).mean()
    )
    df["expected_runs_15"] = df.groupby("player_id")["runs_scored"].transform(
        lambda x: x.shift(1).rolling(15, min_periods=1).mean()
    )

    # --- Form metrics ---
    df["recent_form"] = df["runs_avg_5_lagged"] - df["runs_avg_15_lagged"]
    df["momentum"] = df.groupby("player_id")["runs_scored"].transform(
        lambda x: x.shift(1).rolling(3, min_periods=1).mean()
        - x.shift(1).rolling(10, min_periods=1).mean()
    )

    # --- Venue context with enhanced features ---
    venue_avg = (
        df.groupby("venue")["runs_scored"]
        .mean()
        .reset_index()
        .rename(columns={"runs_scored": "venue_avg_runs"})
    )
    df = df.merge(venue_avg, on="venue", how="left")

    # Player's performance at this venue
    venue_player_avg = (
        df.groupby(["player_id", "venue"])["runs_scored"]
        .mean()
        .reset_index()
        .rename(columns={"runs_scored": "player_venue_avg"})
    )
    df = df.merge(venue_player_avg, on=["player_id", "venue"], how="left")
    df["player_venue_avg"] = df["player_venue_avg"].fillna(df["runs_avg_10_lagged"])

    # --- Match context ---
    df["season_numeric"] = df["season"].apply(safe_convert_season)
    df["match_importance"] = df["match_type"].map({"T20": 1, "ODI": 2}).fillna(1)

    # Batting position impact
    position_avg = (
        df.groupby("batting_position")["runs_scored"]
        .mean()
        .reset_index()
        .rename(columns={"runs_scored": "position_avg_runs"})
    )
    df = df.merge(position_avg, on="batting_position", how="left")

    # Days since last match
    df["days_since_last"] = df.groupby("player_id")["date"].diff().dt.days
    df["days_since_last"] = df["days_since_last"].fillna(30)

    # --- Enhanced interactions ---
    df["form_bowling_combo"] = df["runs_avg_5_lagged"] * (
        1 - df["bowling_strength_norm"]
    )
    df["venue_bowling_combo"] = df["venue_avg_runs"] * (1 - df["bowling_strength_norm"])
    df["player_venue_advantage"] = df["player_venue_avg"] - df["venue_avg_runs"]
    df["position_bowling_combo"] = df["position_avg_runs"] * (
        1 - df["bowling_strength_norm"]
    )
    df["recent_vs_career"] = df["runs_avg_5_lagged"] - df["expected_runs_15"]

    return df


# 5 DATA PREPARATION

print_section("5 DATA PREPARATION")
print(" Creating enhanced batting features...")
df_enhanced = create_batting_features(batting_df, bowling_strength_df)
df_enhanced = df_enhanced.replace([np.inf, -np.inf], np.nan)

print("\n Data Diagnostics:")
print(f" Enhanced shape: {df_enhanced.shape}")
print(
    f" Target - Mean: {df_enhanced['runs_scored'].mean():.3f}, Std: {df_enhanced['runs_scored'].std():.3f}"
)

# Handle NaN values
numeric_cols = df_enhanced.select_dtypes(include=[np.number]).columns
df_enhanced[numeric_cols] = df_enhanced[numeric_cols].fillna(0)

print(" Data cleaning completed")

# ADD ICC TEAM RANKINGS

def add_icc_team_rankings(df, odi_rankings, t20_rankings):
    """
    Add ICC team rankings as features based on match type
    """
    print(" Adding ICC team rankings...")

    # Create ranking dictionaries
    odi_ranking_dict = dict(zip(t20_rankings['Team'], t20_rankings['rating']))
    t20_ranking_dict = dict(zip(odi_rankings['Team'], odi_rankings['rating']))

    # Add batting team ranking
    df['batting_team_rating'] = df.apply(
        lambda x: odi_ranking_dict[x['batting_team']] if x['match_type'] == 'ODI'
        else t20_ranking_dict.get(x['batting_team'], 100),  # Default 100 if not found
        axis=1
    )

    # Add opponent team ranking
    df['opponent_team_rating'] = df.apply(
        lambda x: odi_ranking_dict[x['opponent_team']] if x['match_type'] == 'ODI'
        else t20_ranking_dict.get(x['opponent_team'], 100),
        axis=1
    )

    # Calculate team strength advantage
    df['team_strength_advantage'] = df['batting_team_rating'] - df['opponent_team_rating']

    # Normalize ratings (0-1 scale)
    max_rating = max(df['batting_team_rating'].max(), df['opponent_team_rating'].max())
    df['batting_team_strength'] = df['batting_team_rating'] / max_rating
    df['opponent_team_strength'] = df['opponent_team_rating'] / max_rating

    print(f" Added ICC rankings for {len(df['batting_team'].unique())} teams")
    return df

#  ICC rankings data
odi_rankings_data = {
    'Team': ['Afghanistan', 'Australia', 'Bangladesh', 'Canada', 'England', 'India',
             'Ireland', 'Namibia', 'Nepal', 'Netherlands', 'New Zealand', 'Oman',
             'Pakistan', 'Scotland', 'South Africa', 'Sri Lanka', 'UAE', 'USA',
             'West Indies', 'Zimbabwe', 'Hong Kong', 'Kuwait', 'Uganda'],  # Added missing teams
    'rating': [95, 109, 76, 16, 86, 122, 52, 21, 27, 40, 111, 35, 101, 46, 98, 103, 11, 44, 79, 54, 25, 30, 20]  # Added ratings for missing teams
}

t20_rankings_data = {
    'Team': ['Afghanistan', 'Australia', 'Bangladesh', 'Canada', 'England', 'India',
             'Ireland', 'Namibia', 'Nepal', 'Netherlands', 'New Zealand', 'Oman',
             'Pakistan', 'PNG', 'Scotland', 'South Africa', 'Sri Lanka', 'UAE',
             'Uganda', 'USA', 'West Indies', 'Zimbabwe', 'Hong Kong', 'Kuwait'],  # Added missing teams
    'rating': [220, 267, 223, 154, 258, 272, 201, 181, 176, 182, 251, 150, 234, 136, 182, 240, 230, 178, 142, 175, 237, 199, 127, 130]  # Added ratings for missing teams
}

odi_rankings = pd.DataFrame(odi_rankings_data)
t20_rankings = pd.DataFrame(t20_rankings_data)
# Add to your feature engineering (AFTER creating df_enhanced, BEFORE one-hot encoding)
print_section("ADD ICC TEAM RANKINGS")
df_enhanced = add_icc_team_rankings(df_enhanced, odi_rankings, t20_rankings)

# 6 FEATURE SET - ENHANCED FOR BATTING

print_section("6 FEATURE SET - ENHANCED FOR BATTING")
enhanced_features = [
    # Core historical features
    "vs_opponent_avg_10_lagged",
    "runs_avg_5_lagged",
    "runs_avg_10_lagged",
    "runs_avg_15_lagged",
    "sr_avg_5_lagged",
    "sr_avg_10_lagged",
    # Boundary hitting
    "boundary_rate_5_lagged",
    "boundaries_per_ball",
    # Career expectations
    "expected_runs_5",
    "expected_runs_10",
    "expected_runs_15",
    # Form and momentum
    "recent_form",
    "momentum",
    # Venue context
    "venue_avg_runs",
    "player_venue_avg",
    "player_venue_advantage",
    # Bowling strength (NEW - from bowling data)
    "bowling_strength_norm",
    "opponent_economy_last_5",
    "opponent_wickets_last_5",
    "opponent_dot_pct_last_5",
    "venue_opponent_economy",
    "venue_opponent_wickets",
    "venue_opponent_dot_pct",
    # Match context
    "season_numeric",
    "match_importance",
    "days_since_last",
    "position_avg_runs",
    "batting_position",
    # Enhanced interactions
    "form_bowling_combo",
    "venue_bowling_combo",
    "position_bowling_combo",
    "recent_vs_career",

    # NEW: ICC Team Rankings
    "batting_team_strength",
    "opponent_team_strength",
    "team_strength_advantage",
]

print(f" Using {len(enhanced_features)} enhanced features")

# One-hot encode categoricals
for col in ["venue", "opponent_team", "match_type", "batting_team"]:
    top_categories = df_enhanced[col].value_counts().head(15).index
    df_enhanced[col] = df_enhanced[col].where(
        df_enhanced[col].isin(top_categories), "Other" #All other rare categories are replaced
    )

df_enhanced = pd.get_dummies(
    df_enhanced,
    columns=["venue", "opponent_team", "match_type", "batting_team"],
    drop_first=True,
)

# creates new binary columns: like venue_Lords, venue_MCG, opponent_team_Australia, match_type_T20

# Sanitize column names
df_enhanced.columns = (
    df_enhanced.columns.str.replace(r'[,\(\)"\\\/]', "", regex=True)
    .str.replace(" ", "_")
    .str.replace("__", "_")
)

print(f" Final features: {len(df_enhanced.columns)} columns")

target = "runs_scored"

X = df_enhanced[
    [
        c
        for c in df_enhanced.columns
        if c in enhanced_features
        or c.startswith(("venue_", "opponent_team_", "match_type_", "batting_team_"))
    ]
]
y = df_enhanced[target]
groups = df_enhanced["player_id"]

print(f" Final dataset shape: {X.shape}")

# 7 LIGHTGBM CONFIGURATION - OPTIMIZED FOR BATTING

print_section("7 LIGHTGBM CONFIGURATION - OPTIMIZED FOR BATTING")

# batting setting
params_optimized = {
    "objective": "regression",     # Predict continuous values (runs)
    "metric": "rmse",              # Evaluate model using RMSE
    "learning_rate": 0.01,         # Slow and stable learning
    "num_leaves": 127,             # Controls model complexity (more leaves = more power)
    "min_data_in_leaf": 20,        # Minimum samples per leaf (prevents overfitting)
    "max_depth": 10,               # Maximum depth of each tree
    "subsample": 0.8,              # Use 80% of rows per tree (reduces overfitting)
    "colsample_bytree": 0.8,       # Use 80% of features per tree
    "reg_alpha": 0.1,              # L1 regularization (reduces complexity)
    "reg_lambda": 0.2,             # L2 regularization (prevents overfitting)
    "min_split_gain": 0.01,        # Minimum gain needed to make a split
    "verbose": 1,                 # log during training
}


print(" Using performance-optimized parameters")

# 8 GROUP K-FOLD TRAINING

print_section("8 GROUP K-FOLD TRAINING")
gkf = GroupKFold(n_splits=5)
mae_scores, models, best_iters = [], [], []

print(f"\n Starting LightGBM training ({X.shape[1]} features)...")

for fold, (tr_idx, va_idx) in enumerate(gkf.split(X, y, groups)):
    print(f"\n===== Fold {fold + 1} =====")
    X_tr, X_va = X.iloc[tr_idx], X.iloc[va_idx]
    y_tr, y_va = y.iloc[tr_idx], y.iloc[va_idx]

    d_tr = lgb.Dataset(X_tr, y_tr)
    d_va = lgb.Dataset(X_va, y_va, reference=d_tr)

    model = lgb.train(
        params_optimized,
        d_tr,
        num_boost_round=1500,
        valid_sets=[d_tr, d_va],
        valid_names=["train", "valid"],
        callbacks=[
            lgb.early_stopping(stopping_rounds=150, verbose=False),
            lgb.log_evaluation(period=100),
        ],
    )

    # Get predictions
    train_preds = model.predict(X_tr, num_iteration=model.best_iteration)
    val_preds = model.predict(X_va, num_iteration=model.best_iteration)

    train_mae = mean_absolute_error(y_tr, train_preds)
    val_mae = mean_absolute_error(y_va, val_preds)

    mae_scores.append(val_mae)
    best_iters.append(model.best_iteration)
    models.append(model)

    print(f" Fold {fold + 1} MAE: {val_mae:.3f} (best iter: {model.best_iteration})")
    print(f" Train MAE: {train_mae:.3f} | Gap: {train_mae - val_mae:.3f}")

print(f"\n Average MAE: {np.mean(mae_scores):.3f}  {np.std(mae_scores):.3f}")
print(f" Best iterations: {best_iters}")

# 9 FINAL MODEL TRAINING

print_section("9 FINAL MODEL TRAINING")
best_rounds = max(int(np.mean(best_iters)), 1000)
print(f"\n Training final model on full dataset for {best_rounds} rounds...")

final_model = lgb.train(
    params_optimized,
    lgb.Dataset(X, y),
    num_boost_round=best_rounds,
    callbacks=[lgb.log_evaluation(period=200)],
)

final_model.save_model("/content/final_batting_lgbm.txt")
joblib.dump(final_model, "/content/final_batting_lgbm.pkl")

print("\n Final model trained and saved successfully!")

#  FEATURE IMPORTANCE & ANALYSIS

print_section("FEATURE IMPORTANCE & ANALYSIS")
print("\n Top 20 Feature Importance:")
imp = final_model.feature_importance(importance_type="gain")
names = final_model.feature_name()
fi_df = (
    pd.DataFrame({"feature": names, "importance": imp})
    .sort_values("importance", ascending=False)
    .head(20)
)
print(fi_df.to_string(index=False))

print(f"\n FINAL BATTING MODEL PERFORMANCE:")
print(f"   Average MAE: {np.mean(mae_scores):.3f}")
print(f"   Standard Deviation: {np.std(mae_scores):.3f}")
print(f"   Best iteration: {best_rounds}")
print(f"   Features used: {X.shape[1]}")
print(f"   Target Mean: {y.mean():.3f}")

# Performance analysis
if np.mean(mae_scores) < y.std():
    print(f" SUCCESS! MAE is better than baseline standard deviation")
else:
    print(f"  Model performance needs improvement")

#  REALISTIC BATTING PREDICTOR


def realistic_batting_predictor_dynamic(
    player_id, opponent_team, venue, match_type, batting_position
):
    """
    Realistic integer runs prediction with DYNAMIC data-driven factors
    """
    print(f"\n MAKING PREDICTION FOR {player_id}")
    print("=" * 50)

    # Get player data
    player_df = df_enhanced[df_enhanced["player_id"] == player_id].sort_values("date")
    if player_df.empty:
        return f" Player {player_id} not found in dataset."

    # Get player profile
    player_profile = player_profiles[player_profiles["player_id"] == player_id]
    if len(player_profile) == 0:
        player_type = " UNKNOWN PLAYER"
        avg_runs = player_df["runs_scored"].mean() if len(player_df) > 0 else 20
    else:
        player_type = player_profile["player_type"].iloc[0]
        avg_runs = player_profile["avg_runs"].iloc[0]
        player_name = player_profile["name"].iloc[0]

    # Get venue effect
    venue_effect = venue_effects[venue_effects["venue"] == venue]
    if len(venue_effect) == 0:
        venue_factor = 1.0
        venue_type = " NEUTRAL (Unknown)"
    else:
        venue_factor = venue_effect["final_venue_factor"].iloc[0]
        venue_type = venue_effect["venue_type"].iloc[0]

    # Player stats
    player_recent = (
        player_df["runs_scored"].tail(10).mean() if len(player_df) > 0 else avg_runs
    )
    player_sr = player_df["strike_rate"].mean() if len(player_df) > 0 else 120

    # Base prediction from player's capability
    base_prediction = max(avg_runs, player_recent)

    # === BATTER QUALITY BONUS ===
    quality_bonus = 0.0
    if "WORLD-CLASS" in player_type:
        quality_bonus = 8.0
    elif "SOLID" in player_type or "RELIABLE" in player_type:
        quality_bonus = 4.0
    elif "DEPENDABLE" in player_type:
        quality_bonus = 2.0
    elif "HARD-HITTING" in player_type:
        quality_bonus = 3.0

    base_prediction += quality_bonus

    # === OPPONENT BOWLING STRENGTH ===
    # Get opponent bowling strength from the data
    opponent_strength_data = batting_df[batting_df["opponent_team"] == opponent_team]
    if len(opponent_strength_data) > 0:
        opponent_strength = opponent_strength_data["bowling_strength_norm"].mean()
    else:
        opponent_strength = 0.5  # Default neutral

    # Convert bowling strength to factor (0-1  factor)
    opponent_factor = 1.0 + (0.5 - opponent_strength)  # Higher strength = lower factor

    # Categorize opponent
    if opponent_strength > 0.7:
        opponent_type = " ELITE BOWLING"
        opponent_factor *= 0.8
    elif opponent_strength > 0.6:
        opponent_type = " STRONG BOWLING"
        opponent_factor *= 0.9
    elif opponent_strength < 0.4:
        opponent_type = " WEAK BOWLING"
        opponent_factor *= 1.2
    elif opponent_strength < 0.3:
        opponent_type = " VERY WEAK BOWLING"
        opponent_factor *= 1.4
    else:
        opponent_type = " MEDIUM BOWLING"

    # === BATTING POSITION EFFECT ===
    if batting_position <= 2:  # Openers
        position_factor = 1.3
        position_type = " OPENING BATTER"
    elif batting_position <= 4:  # Top order
        position_factor = 1.2
        position_type = " TOP ORDER"
    elif batting_position <= 6:  # Middle order
        position_factor = 1.0
        position_type = " MIDDLE ORDER"
    else:  # Lower order
        position_factor = 0.7
        position_type = " LOWER ORDER"

    # === FORM EFFECT ===
    if len(player_df) >= 5:
        recent_5 = player_df["runs_scored"].tail(5).mean()
        recent_15 = (
            player_df["runs_scored"].tail(15).mean()
            if len(player_df) >= 15
            else recent_5
        )
        recent_form = recent_5 - recent_15
    else:
        recent_form = 0

    if recent_form > 15:
        form_factor = 1.3
        form_type = " EXCELLENT FORM"
    elif recent_form > 8:
        form_factor = 1.15
        form_type = " GOOD FORM"
    elif recent_form < -15:
        form_factor = 0.7
        form_type = " POOR FORM"
    elif recent_form < -8:
        form_factor = 0.85
        form_type = " BELOW AVERAGE"
    else:
        form_factor = 1.0
        form_type = " NORMAL FORM"

    # === CALCULATE REALISTIC INTEGER PREDICTION ===
    realistic_float = (
        base_prediction * opponent_factor * venue_factor * position_factor * form_factor
    )

    # Convert to integer with realistic cricket logic
    if realistic_float >= 80:
        runs_predicted = int(realistic_float)  # Big score - keep exact
    elif realistic_float >= 50:
        runs_predicted = int(round(realistic_float / 5) * 5)  # Round to nearest 5
    elif realistic_float >= 25:
        runs_predicted = int(round(realistic_float / 2) * 2)  # Round to nearest 2
    else:
        runs_predicted = int(round(realistic_float))  # Round normally

    # Ensure realistic constraints
    if batting_position >= 7 and runs_predicted > 35:  # Lower order limit
        runs_predicted = min(35, runs_predicted)

    if "WORLD-CLASS" in player_type and runs_predicted < 20:  # Elite batter floor
        runs_predicted = max(20, runs_predicted)

    # Display prediction
    player_display_name = player_name if "player_name" in locals() else player_id
    print(f" Player: {player_display_name} ({player_type})")
    print(f" vs {opponent_team} ({opponent_type})")
    print(f" {venue} ({venue_type})")
    print(f" {match_type} | Batting: {batting_position} ({position_type})")
    print(f" {form_type}")
    print(f" Base: {base_prediction:.1f} (incl. {quality_bonus:+} quality bonus)")
    print(
        f" Multipliers: Opponent {opponent_factor:.2f}x | Venue {venue_factor:.2f}x"
    )
    print(f"   Position {position_factor:.2f}x | Form {form_factor:.2f}x")
    print(f" Raw: {realistic_float:.1f}  FINAL: {runs_predicted} runs")

    # Performance rating
    if runs_predicted >= 75:
        print(f"    CENTURY CONTENDER! ")
    elif runs_predicted >= 50:
        print(f"    Half-century likely! ")
    elif runs_predicted >= 35:
        print(f"    Good contribution! ")
    elif runs_predicted >= 20:
        print(f"    Decent innings! ")
    elif runs_predicted >= 10:
        print(f"     Modest contribution! ")
    else:
        print(f"    Low score expected ")

    print("=" * 50)
    return runs_predicted


#  TEST THE PREDICTOR

print_section("TEST THE PREDICTOR")
print(" TESTING REALISTIC PREDICTOR")
print(SECTION_LINE)
# Get some real player IDs from the data for testing
sample_players = df_enhanced["player_id"].value_counts().head(8).index

test_cases = []
for i, player_id in enumerate(sample_players[:4]):
    test_cases.append(
        (
            player_id,
            "Australia",  # Strong opponent
            batting_df["venue"].iloc[0],  # Use first venue in data
            "T20",
            3,  # Top order
        )
    )

for i, player_id in enumerate(sample_players[4:8]):
    test_cases.append(
        (
            player_id,
            "United States",  # Weak opponent
            batting_df["venue"].iloc[1],  # Use second venue in data
            "ODI",
            6,  # Middle order
        )
    )

print("\nREALISTIC BATTING PREDICTIONS\n")

for player_id, opponent, venue, match_type, position in test_cases:
    try:
        prediction = realistic_batting_predictor_dynamic(
            player_id=player_id,
            opponent_team=opponent,
            venue=venue,
            match_type=match_type,
            batting_position=position,
        )
    except Exception as e:
        print(f" Error predicting for {player_id}: {e}")
        continue

print(" All predictions completed!")

model_dir = '/content/drive/MyDrive/CricAI/models/batting'
os.makedirs(model_dir, exist_ok=True)

# Save the model
model_path = os.path.join(model_dir, 'final_batting_lgbm.pkl')
joblib.dump(model, model_path)

print(f" Model saved to: {model_path}")

# Check if "Sri lanka" vs "Sri Lanka" matters
print("Unique opponents in data:")
print(bowling_strength_df["opponent_team"].unique())

def realistic_batting_predictor_dynamic(
    player_id, opponent_team, venue, match_type, batting_position
):
    """
    Realistic integer runs prediction with data-driven factors
    """
    # Get player data
    player_df = df_enhanced[df_enhanced["player_id"] == player_id].sort_values("date")
    if player_df.empty:
        return f"Player {player_id} not found in dataset."

    # Get player profile
    player_profile = player_profiles[player_profiles["player_id"] == player_id]
    if len(player_profile) == 0:
        player_type = "UNKNOWN PLAYER"
        avg_runs = player_df["runs_scored"].mean() if len(player_df) > 0 else 20
        player_name = player_id
    else:
        player_type = player_profile["player_type"].iloc[0]
        avg_runs = player_profile["avg_runs"].iloc[0]
        player_name = player_profile["name"].iloc[0]

    # Get venue effect
    venue_effect = venue_effects[venue_effects["venue"] == venue]
    if len(venue_effect) == 0:
        venue_factor = 1.0
        venue_type = "NEUTRAL"
    else:
        venue_factor = venue_effect["final_venue_factor"].iloc[0]
        venue_type = venue_effect["venue_type"].iloc[0]

    # Player stats
    player_recent = (
        player_df["runs_scored"].tail(10).mean() if len(player_df) > 0 else avg_runs
    )

    # Base prediction from player's capability
    base_prediction = max(avg_runs, player_recent)

    # Batter quality bonus
    quality_bonus = 0.0
    if "WORLD-CLASS" in player_type:
        quality_bonus = 8.0
    elif "SOLID" in player_type or "RELIABLE" in player_type:
        quality_bonus = 4.0
    elif "DEPENDABLE" in player_type:
        quality_bonus = 2.0
    elif "HARD-HITTING" in player_type:
        quality_bonus = 3.0

    base_prediction += quality_bonus

    # === IMPROVED OPPONENT BOWLING STRENGTH ===
    # Normalize case for matching
    opponent_team_normalized = opponent_team.strip().title()

    # Get opponent bowling strength with case-insensitive matching
    opponent_data = bowling_strength_df[
        bowling_strength_df["opponent_team"].str.strip().str.title() == opponent_team_normalized
    ]

    if len(opponent_data) > 0:
        opponent_strength = opponent_data["bowling_strength_norm"].mean()
        actual_opponent_name = opponent_data["opponent_team"].iloc[0]
        strength_source = "exact match"
    else:
        # Fallback: Use team categorization
        major_teams = ["Australia", "India", "England", "New Zealand", "South Africa", "Pakistan"]
        strong_teams = ["Sri Lanka", "West Indies", "Bangladesh"]
        associate_teams = ["United States", "Netherlands", "Ireland", "Scotland", "UAE", "Canada", "Oman", "Nepal"]

        if opponent_team_normalized in major_teams:
            major_data = bowling_strength_df[bowling_strength_df["opponent_team"].isin(major_teams)]
            opponent_strength = major_data["bowling_strength_norm"].mean() if len(major_data) > 0 else 0.65
            strength_source = "major team average"
        elif opponent_team_normalized in strong_teams:
            strong_data = bowling_strength_df[bowling_strength_df["opponent_team"].isin(strong_teams)]
            opponent_strength = strong_data["bowling_strength_norm"].mean() if len(strong_data) > 0 else 0.55
            strength_source = "strong team average"
        elif opponent_team_normalized in associate_teams:
            associate_data = bowling_strength_df[bowling_strength_df["opponent_team"].isin(associate_teams)]
            opponent_strength = associate_data["bowling_strength_norm"].mean() if len(associate_data) > 0 else 0.4
            strength_source = "associate team average"
        else:
            opponent_strength = 0.5
            strength_source = "default neutral"

        actual_opponent_name = opponent_team_normalized

    opponent_factor = 1.0 + (0.5 - opponent_strength)

    # Categorize opponent
    if opponent_strength > 0.7:
        opponent_type = "ELITE BOWLING"
        opponent_factor *= 0.8
    elif opponent_strength > 0.6:
        opponent_type = "STRONG BOWLING"
        opponent_factor *= 0.9
    elif opponent_strength < 0.4:
        opponent_type = "WEAK BOWLING"
        opponent_factor *= 1.2
    elif opponent_strength < 0.3:
        opponent_type = "VERY WEAK BOWLING"
        opponent_factor *= 1.4
    else:
        opponent_type = "MEDIUM BOWLING"

    # Batting position effect
    if batting_position <= 2:
        position_factor = 1.3
        position_type = "OPENING"
    elif batting_position <= 4:
        position_factor = 1.2
        position_type = "TOP ORDER"
    elif batting_position <= 6:
        position_factor = 1.0
        position_type = "MIDDLE ORDER"
    else:
        position_factor = 0.7
        position_type = "LOWER ORDER"

    # Form effect
    if len(player_df) >= 5:
        recent_5 = player_df["runs_scored"].tail(5).mean()
        recent_15 = (
            player_df["runs_scored"].tail(15).mean()
            if len(player_df) >= 15
            else recent_5
        )
        recent_form = recent_5 - recent_15
    else:
        recent_form = 0

    if recent_form > 15:
        form_factor = 1.3
        form_type = "EXCELLENT FORM"
    elif recent_form > 8:
        form_factor = 1.15
        form_type = "GOOD FORM"
    elif recent_form < -15:
        form_factor = 0.7
        form_type = "POOR FORM"
    elif recent_form < -8:
        form_factor = 0.85
        form_type = "BELOW AVERAGE"
    else:
        form_factor = 1.0
        form_type = "NORMAL FORM"

    # Calculate realistic integer prediction
    realistic_float = (
        base_prediction * opponent_factor * venue_factor * position_factor * form_factor
    )

    # Convert to integer with realistic cricket logic
    if realistic_float >= 80:
        runs_predicted = int(realistic_float)
    elif realistic_float >= 50:
        runs_predicted = int(round(realistic_float / 5) * 5)
    elif realistic_float >= 25:
        runs_predicted = int(round(realistic_float / 2) * 2)
    else:
        runs_predicted = int(round(realistic_float))

    # Ensure realistic constraints
    if batting_position >= 7 and runs_predicted > 35:
        runs_predicted = min(35, runs_predicted)

    if "WORLD-CLASS" in player_type and runs_predicted < 20:
        runs_predicted = max(20, runs_predicted)

    # Display prediction
    player_display_name = player_name if "player_name" in locals() else player_id

    print(f"PREDICTION: {player_display_name} - {runs_predicted} runs")
    print(f"Context: vs {actual_opponent_name} at {venue} | Position: {batting_position} ({position_type})")
    print(f"Factors: {player_type} | {opponent_type} | {venue_type} | {form_type}")
    print(f"Strength source: {strength_source} ({opponent_strength:.3f})")

    return runs_predicted

# Multiple predictions at once
predictions_list = [
    # {
    #     "player_id": "740742ef",
    #     "opponent_team": "Sri lanka",
    #     "venue": "Melbourne Cricket Ground",
    #     "match_type": "T20",
    #     "batting_position": 5
    # },
    # {
    #     "player_id": "8a75e999",
    #     "opponent_team": "India",
    #     "venue": "Sydney Cricket Ground",
    #     "match_type": "ODI",
    #     "batting_position": 4
    # },
    {
        "player_id": "ba607b88",
        "opponent_team": "Nepal",
        "venue": "Lord's",
        "match_type": "T20",
        "batting_position": 6
    },
    {
        "player_id": "ba607b88",
        "opponent_team": "England",
        "venue": "Lord's",
        "match_type": "T20",
        "batting_position": 6
    },
    {
        "player_id": "ba607b88",
        "opponent_team": "Afaganistan",
        "venue": "Lord's",
        "match_type": "T20",
        "batting_position": 6
    },
    {
        "player_id": "ba607b88",
        "opponent_team": "Pakistan",
        "venue": "Lord's",
        "match_type": "T20",
        "batting_position": 6
    }
]

for match in predictions_list:
    runs = realistic_batting_predictor_dynamic(**match)
    print(f"{match['player_id']}: {runs} runs")